#include "hal/capture.hpp"

#include "capture.pio.h" // generated by pico_generate_pio_header (see CMake)
#include "hardware/dma.h"
#include "hardware/pio.h"

#include <cstdint>

// The PIO SM + DMA emit and store every edge with ZERO CPU per edge. Only
// drain() (called opportunistically every core1 loop iteration) touches the
// ring, and it is marked __time_critical_func so its read/decode loop executes
// from RAM (flash-XIP stalls never perturb it, though correctness does not
// depend on timing here -- the DMA already captured everything).

namespace hal {

// log2(kCaptureRingLen) -- used for the DMA hardware ring-wrap. kCaptureRingLen
// must be a power of two (checked below).
static constexpr std::uint32_t ring_size_bits() {
  std::uint32_t n = kCaptureRingLen, b = 0;
  while (n > 1) {
    n >>= 1;
    ++b;
  }
  return b;
}
static_assert((kCaptureRingLen & (kCaptureRingLen - 1)) == 0, "ring len must be power of two");

// Add the capture program to `pio` at most once; subsequent channels on the same
// block reuse the cached offset. pio_add_program returns -1 (no panic) if the 32
// instruction slots can't hold another copy, so a per-channel copy silently breaks
// the 3rd+ channel on a block -- sharing one copy avoids that entirely.
uint Capture::load_program(PIO pio) {
  for (auto& pl : loaded_) {
    if (pl.pio == pio) {
      return pl.offset;
    }
  }
  uint offset = static_cast<uint>(pio_add_program(pio, &capture_program));
  for (auto& pl : loaded_) {
    if (pl.pio == nullptr) {
      pl.pio = pio;
      pl.offset = offset;
      break;
    }
  }
  return offset;
}

void Capture::init_channel(std::size_t slot, PIO pio, uint pin, ChannelId ch_id, bool idle_high) {
  CaptureChannel& c = chans_[slot];
  c.pio = pio;
  c.pin = pin;
  c.ch_id = ch_id.v;
  c.read_idx = 0;
  // Polarity is now sampled per edge in PIO (capture word bit 31), so decode does
  // not depend on this seed -- decode_capture overwrites c.level on the first
  // edge. We keep `idle_high` only as a harmless initial value (the pin's expected
  // resting level) for any read before the first captured edge.
  c.level = idle_high;
  // 31-bit timebase: bit 31 of each capture word carries the level, so the counter
  // payload is 31 bits (core::kCaptureTsBits). See capture.pio / capture_decode.
  c.tb = core::Timebase64{core::kCaptureTsBits};

  // Load the capture program ONCE per PIO block and share the offset across every
  // SM on that block (they run the identical program). Loading a per-channel copy
  // would blow the 32-slot PIO instruction memory once 3+ channels share a block.
  c.offset = load_program(pio);
  c.sm = static_cast<uint>(pio_claim_unused_sm(pio, true));
  capture_program_init(pio, c.sm, c.offset, pin);

  c.dma = dma_claim_unused_channel(true);

  if (slot + 1 > nchans_) {
    nchans_ = slot + 1;
  }
}

void Capture::init_ignition(std::size_t slot, PIO pio, uint pin, std::uint8_t ch_id) {
  init_channel(slot, pio, pin, ChannelId{ch_id}, /*idle_high=*/true);
}

void Capture::init_pickup_selfcapture(std::size_t slot, PIO pio, uint pin, std::uint8_t ch_id) {
  init_channel(slot, pio, pin, ChannelId{ch_id}, /*idle_high=*/false);
}

// GP19 tach reads the DUT ignitor tach output (present only with the real
// ignitor). It is a 12 V open-collector node that idles HIGH, so it shares the
// idle-HIGH polarity path with init_ignition (first edge FALLING).
void Capture::init_tach(std::size_t slot, PIO pio, uint pin, std::uint8_t ch_id) {
  init_channel(slot, pio, pin, ChannelId{ch_id}, /*idle_high=*/true);
}

// Arm the DMA channel to copy RX-FIFO words into the channel's ring, paced by
// the SM's RX DREQ, with a hardware ring wrap on the WRITE address so it loops
// forever with no reconfiguration. A large transfer_count (never expected to
// exhaust between reboots at these edge rates) keeps it running; drain() derives
// the write position from the DMA's live write_addr register.
void Capture::arm_dma(CaptureChannel& c) {
  dma_channel_config dc = dma_channel_get_default_config(static_cast<uint>(c.dma));
  channel_config_set_transfer_data_size(&dc, DMA_SIZE_32);
  channel_config_set_read_increment(&dc, false); // always the same FIFO register
  channel_config_set_write_increment(&dc, true);
  // Hardware ring wrap on the WRITE address: wraps every 2^bits BYTES back to
  // the ring base, so the DMA cycles through `ring` endlessly. Requires `ring`
  // aligned to that byte size (see CaptureChannel alignas).
  channel_config_set_ring(&dc, /*write=*/true, ring_size_bits() + 2 /*bytes: *4*/);
  channel_config_set_dreq(&dc, pio_get_dreq(c.pio, c.sm, false)); // RX DREQ

  dma_channel_configure(static_cast<uint>(c.dma), &dc,
                        c.ring.data(),     // write: ring base
                        &c.pio->rxf[c.sm], // read: RX FIFO
                        0xFFFFFFFFu,       // effectively endless
                        false);            // don't start yet
}

void Capture::start() {
  // Arm every DMA channel first so no edge is lost when the SMs come alive.
  std::uint32_t sm_mask = 0;
  for (std::size_t i = 0; i < nchans_; ++i) {
    CaptureChannel& c = chans_[i];
    if (!c.pio) {
      continue;
    }
    pio_sm_set_enabled(c.pio, c.sm, false);
    pio_sm_clear_fifos(c.pio, c.sm);
    pio_sm_restart(c.pio, c.sm);
    // Re-seed X = 0xFFFFFFFF and jump to program start for a deterministic phase.
    pio_sm_exec(c.pio, c.sm, pio_encode_jmp(c.offset));
    pio_sm_exec(c.pio, c.sm, pio_encode_mov_not(pio_x, pio_null));
    arm_dma(c);
    dma_channel_start(static_cast<uint>(c.dma));
    c.read_idx = 0;
    c.started = true;
  }

  // Enable all SMs in one synchronized write PER PIO block so counters in the
  // same block are phase-locked. Blocks are still started as close together as
  // two consecutive register writes (sub-microsecond) -- acceptable since the
  // shared timebase only needs the SMs to advance at the same RATE, and any
  // constant phase offset between the two blocks cancels in per-channel deltas.
  for (int blk = 0; blk < NUM_PIOS; ++blk) {
    PIO pio = PIO_INSTANCE(blk);
    sm_mask = 0;
    for (std::size_t i = 0; i < nchans_; ++i) {
      if (chans_[i].pio == pio) {
        sm_mask |= (1u << chans_[i].sm);
      }
    }
    if (sm_mask) {
      pio_enable_sm_mask_in_sync(pio, sm_mask);
    }
  }
}

void Capture::stop() {
  for (std::size_t i = 0; i < nchans_; ++i) {
    CaptureChannel& c = chans_[i];
    if (!c.pio) {
      continue;
    }
    pio_sm_set_enabled(c.pio, c.sm, false);
    dma_channel_abort(static_cast<uint>(c.dma));
    pio_sm_clear_fifos(c.pio, c.sm);
    c.started = false;
  }
}

std::size_t __time_critical_func(Capture::drain_channel)(CaptureChannel& c, CaptureEvent* out,
                                                         std::size_t max) {
  // Current DMA write index = (live write_addr - ring base) / 4, modulo len.
  const std::uintptr_t base = reinterpret_cast<std::uintptr_t>(c.ring.data());
  const std::uintptr_t waddr =
      static_cast<std::uintptr_t>(dma_channel_hw_addr(static_cast<uint>(c.dma))->write_addr);
  const std::size_t write_idx =
      static_cast<std::size_t>((waddr - base) / sizeof(std::uint32_t)) % kCaptureRingLen;

  std::size_t n = 0;
  while (c.read_idx != write_idx && n < max) {
    const std::uint32_t raw = c.ring[c.read_idx];
    CaptureEvent& e = out[n];
    e.ticks = core::decode_capture(raw, c.tb, c.level);
    e.rising = c.level; // post-flip level == this edge's new steady level
    e.ch = c.ch_id;
    ++n;
    c.read_idx = (c.read_idx + 1) % kCaptureRingLen;
  }
  return n;
}

std::size_t __time_critical_func(Capture::drain)(CaptureEvent* out, std::size_t max) {
  std::size_t total = 0;
  for (std::size_t i = 0; i < nchans_ && total < max; ++i) {
    CaptureChannel& c = chans_[i];
    if (!c.started) {
      continue;
    }
    total += drain_channel(c, out + total, max - total);
  }
  return total;
}

} // namespace hal
